### ISSUE TITLE
Use matplotlib in place of gnuplot for plotting

### ISSUE THREAD

**Issue by graeme-winter** [xia2/screen19#57]
Or even, plotly - just ran and got a stack trace

**Comment by benjaminhwilliams** [comment]
The use of Gnuplot was a design decision that predates me — an effort to produce plots in the terminal, since Matplotlib has never had a stable and widely adopted terminal backend.  I tried and failed once before to find a suitable alternative, but I could try again.  I notice that there are new options out there, like [matrach/matplotlib-terminal](https://github.com/matrach/matplotlib-terminal).

**Comment by benjaminhwilliams** [comment]
@graeme-winter, a few more details would be handy.  Could you paste the trace here?

**Comment by graeme-winter** [comment]
Wilco, though I will have to uninstall `gnuplot` to reproduce

FWIW I tend to find the `Agg` backend (which I have no idea _why_ it is so named) works well

**Comment by benjaminhwilliams** [comment]
Yes, for making images, but not for creating in-terminal ASCII-art plots.  And that is what we need Gnuplot for here.

**Comment by graeme-winter** [comment]
_

> Yes, for making images, but not for creating in-terminal ASCII-art plots. And that is what we need Gnuplot for here.

_Ah_ that is rather different, OK then

**Comment by graeme-winter** [comment]
As pointed out by @benjaminhwilliams no good alternative for the ascii art -> closing
